version: 2

jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
        environment:
          BUILD_ENV: linux
          CMAKE_URL: https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gcc main.c && ./a.out
            export EXIT_CODE=run_ok
            echo 'export TEST=hello' >>$BASH_ENV
            echo "code:" ${EXIT_CODE}
            echo "TEST:" ${TEST}
      - run:
          name: Failed
          command: |
            echo "code:" $?
            echo "on_fail" ${on_fail}
            echo "Fail: exit_code:" $EXIT_CODE
            if [ "${EXIT_CODE}" == "" ]; then
              echo "crash"
            fi
            echo "Test Failed"
          when: on_fail

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
